name: Smoke tests

on: [push]

jobs:
  gerar-swagger:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.561

      - name: Gerando Swagger
        run: clojure -A:swagger

      - run: |
          git config user.name Squad Alpha
          git config user.email github-actions@github.com
          git status
         